arch: 
  - amd64
  - ppc64le
language: java
os: linux
dist: bionic
jdk: openjdk11
before_install:
#  - sudo apt install maven -y
  - export MAVEN_OPTS="-Xmx1024m"
#install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V > neo4j.log
  - tail -300 neo4j.log
  - travis_wait 30 mvn test -B
#  - mvn clean install
